name: Angular GitHub CI

on:
  push:
    branches: [ "main", "Dev", "front-end-test-CI" ]

defaults:
  run:
    working-directory: ./front-end-main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        working-directory: './front-end-main'
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm ci
    - run: npm run build --if-present
    - name: Angular Tests
      run: ng test
