name: Angular GitHub CI

on:
  push:
    branches: [ "main", "Dev", "front-end-test-CI" ]

defaults:
  run:
    working-directory: './front-end-main'
    
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      run: npm install
    - name: Intall CI
      run: npm install
    - name: Run Build
      run: npm run build --if-present
    - name: Angular Tests
      working-directory: './front-end-main'
      run: ng test
